---
- name: "Test NetBox modules"
  connection: local
  hosts: localhost
  gather_facts: False
  collections:
    - netbox.netbox

  vars_files:
    - vars/main.yml

  tasks:
    - name: Create prefix within NetBox with only required information
      netbox_prefix:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          prefix: 10.156.0.0/19
        state: present
